# We specify volumes in override.yml, because volumes don't work well in a
# docker-in-docker setup (the paths of parent host rarely match the nested containers)
version: "3.9"

services:
  postgres:
    ports:
      - "5432:5432"
    volumes:
      - app-db-data:/var/lib/postgresql/data:cached

  backend:
    command: uvicorn --port {{ cookiecutter.backend_port }} --host 0.0.0.0 --reload main:app
    volumes:
      - ./backend:/app:delegated
      - root-home:/root:delegated
    depends_on:
      postgres:
        condition: service_healthy
